repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = 'https://maven.parchmentmc.org'
    }
}

dependencies {
    implementation(fg.deobf("com.ldtteam:blockui:${project.blockUIVersion}")) {
        transitive = false
    }

    compileOnly(fg.deobf("com.ldtteam:domum_ornamentum:${project.domumOrnamentumVersion}:universal")) {
        transitive = false
    }
    runtimeOnly(fg.deobf("com.ldtteam:domum_ornamentum:${project.domumOrnamentumVersion}:universal")) {
        transitive = false
    }
}
